package com.yfann.web.pojo;

import java.math.BigDecimal;

public class ApplyMoney {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.apply_id
     *
     * @mbggenerated
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.apply_user_id
     *
     * @mbggenerated
     */
    private String applyUserId;
    
    /** 申请者 */
    private OaEmployee apply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.authorize_user_id
     *
     * @mbggenerated
     */
    private String authorizeUserId;
    
    /** 权限授予者 */
    private OaEmployee authorize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.importance
     *
     * @mbggenerated
     */
    private String importance;
    
    /** 重要程度 */
    private Dic importanceDic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.apply_kind
     *
     * @mbggenerated
     */
    private String applyKind;
    
    /** 申请种别 */
    private Dic applyKindDic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.apply_status
     *
     * @mbggenerated
     */
    private String applyStatus;
    
    /** 申请状态 */
    private Dic applyStatusDic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.pay_status
     *
     * @mbggenerated
     */
    private String payStatus;
    
    /** 支付状态 */
    private Dic payStatusDic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.target_kind
     *
     * @mbggenerated
     */
    private String targetKind;
    
    /** 目标种别 */
    private Dic targetKindDic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_apply_money.expenditure_remark
     *
     * @mbggenerated
     */
    private String expenditureRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.id
     *
     * @return the value of t_apply_money.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.id
     *
     * @param id the value for t_apply_money.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.apply_id
     *
     * @return the value of t_apply_money.apply_id
     *
     * @mbggenerated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.apply_id
     *
     * @param applyId the value for t_apply_money.apply_id
     *
     * @mbggenerated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.apply_user_id
     *
     * @return the value of t_apply_money.apply_user_id
     *
     * @mbggenerated
     */
    public String getApplyUserId() {
        return applyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.apply_user_id
     *
     * @param applyUserId the value for t_apply_money.apply_user_id
     *
     * @mbggenerated
     */
    public void setApplyUserId(String applyUserId) {
        this.applyUserId = applyUserId == null ? null : applyUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.authorize_user_id
     *
     * @return the value of t_apply_money.authorize_user_id
     *
     * @mbggenerated
     */
    public String getAuthorizeUserId() {
        return authorizeUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.authorize_user_id
     *
     * @param authorizeUserId the value for t_apply_money.authorize_user_id
     *
     * @mbggenerated
     */
    public void setAuthorizeUserId(String authorizeUserId) {
        this.authorizeUserId = authorizeUserId == null ? null : authorizeUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.importance
     *
     * @return the value of t_apply_money.importance
     *
     * @mbggenerated
     */
    public String getImportance() {
        return importance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.importance
     *
     * @param importance the value for t_apply_money.importance
     *
     * @mbggenerated
     */
    public void setImportance(String importance) {
        this.importance = importance == null ? null : importance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.apply_kind
     *
     * @return the value of t_apply_money.apply_kind
     *
     * @mbggenerated
     */
    public String getApplyKind() {
        return applyKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.apply_kind
     *
     * @param applyKind the value for t_apply_money.apply_kind
     *
     * @mbggenerated
     */
    public void setApplyKind(String applyKind) {
        this.applyKind = applyKind == null ? null : applyKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.apply_status
     *
     * @return the value of t_apply_money.apply_status
     *
     * @mbggenerated
     */
    public String getApplyStatus() {
        return applyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.apply_status
     *
     * @param applyStatus the value for t_apply_money.apply_status
     *
     * @mbggenerated
     */
    public void setApplyStatus(String applyStatus) {
        this.applyStatus = applyStatus == null ? null : applyStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.pay_status
     *
     * @return the value of t_apply_money.pay_status
     *
     * @mbggenerated
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.pay_status
     *
     * @param payStatus the value for t_apply_money.pay_status
     *
     * @mbggenerated
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.money
     *
     * @return the value of t_apply_money.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.money
     *
     * @param money the value for t_apply_money.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.target_kind
     *
     * @return the value of t_apply_money.target_kind
     *
     * @mbggenerated
     */
    public String getTargetKind() {
        return targetKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.target_kind
     *
     * @param targetKind the value for t_apply_money.target_kind
     *
     * @mbggenerated
     */
    public void setTargetKind(String targetKind) {
        this.targetKind = targetKind == null ? null : targetKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_apply_money.expenditure_remark
     *
     * @return the value of t_apply_money.expenditure_remark
     *
     * @mbggenerated
     */
    public String getExpenditureRemark() {
        return expenditureRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_apply_money.expenditure_remark
     *
     * @param expenditureRemark the value for t_apply_money.expenditure_remark
     *
     * @mbggenerated
     */
    public void setExpenditureRemark(String expenditureRemark) {
        this.expenditureRemark = expenditureRemark == null ? null : expenditureRemark.trim();
    }

	public OaEmployee getApply() {
		return apply;
	}

	public void setApply(OaEmployee apply) {
		this.apply = apply;
	}

	public OaEmployee getAuthorize() {
		return authorize;
	}

	public void setAuthorize(OaEmployee authorize) {
		this.authorize = authorize;
	}

	public Dic getImportanceDic() {
		return importanceDic;
	}

	public void setImportanceDic(Dic importanceDic) {
		this.importanceDic = importanceDic;
	}

	public Dic getApplyKindDic() {
		return applyKindDic;
	}

	public void setApplyKindDic(Dic applyKindDic) {
		this.applyKindDic = applyKindDic;
	}

	public Dic getApplyStatusDic() {
		return applyStatusDic;
	}

	public void setApplyStatusDic(Dic applyStatusDic) {
		this.applyStatusDic = applyStatusDic;
	}

	public Dic getPayStatusDic() {
		return payStatusDic;
	}

	public void setPayStatusDic(Dic payStatusDic) {
		this.payStatusDic = payStatusDic;
	}

	public Dic getTargetKindDic() {
		return targetKindDic;
	}

	public void setTargetKindDic(Dic targetKindDic) {
		this.targetKindDic = targetKindDic;
	}
    
}