package com.yfann.web.pojo;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_department.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_department.depart_name
     *
     * @mbggenerated
     */
    private String departName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_department.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_department.depart_id
     *
     * @mbggenerated
     */
    private String departId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_department.ID
     *
     * @return the value of t_sys_department.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_department.ID
     *
     * @param id the value for t_sys_department.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_department.depart_name
     *
     * @return the value of t_sys_department.depart_name
     *
     * @mbggenerated
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_department.depart_name
     *
     * @param departName the value for t_sys_department.depart_name
     *
     * @mbggenerated
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_department.remark
     *
     * @return the value of t_sys_department.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_department.remark
     *
     * @param remark the value for t_sys_department.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_department.depart_id
     *
     * @return the value of t_sys_department.depart_id
     *
     * @mbggenerated
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_department.depart_id
     *
     * @param departId the value for t_sys_department.depart_id
     *
     * @mbggenerated
     */
    public void setDepartId(String departId) {
        this.departId = departId == null ? null : departId.trim();
    }
}