package com.yfann.web.pojo;

import java.io.Serializable;
import java.util.Date;

public class MyProduct implements Serializable{
	private static final long serialVersionUID = 167976018538469334L;
	/**授权码授权状态*/
	private Dic accreditStatusDic;
	/**产品*/
	private Product product;
	/**详情*/
	private ProductDetail productDetail;
	/****************************************************************************************************************/
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.smart_code
     *
     * @mbggenerated
     */
    private String smartCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.player_code
     *
     * @mbggenerated
     */
    private String playerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.accredit_user
     *
     * @mbggenerated
     */
    private String accreditUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.accredit_time
     *
     * @mbggenerated
     */
    private Date accreditTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.accredit_status
     *
     * @mbggenerated
     */
    private String accreditStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_my_product.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.id
     *
     * @return the value of t_my_product.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.id
     *
     * @param id the value for t_my_product.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.product_id
     *
     * @return the value of t_my_product.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.product_id
     *
     * @param productId the value for t_my_product.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.smart_code
     *
     * @return the value of t_my_product.smart_code
     *
     * @mbggenerated
     */
    public String getSmartCode() {
        return smartCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.smart_code
     *
     * @param smartCode the value for t_my_product.smart_code
     *
     * @mbggenerated
     */
    public void setSmartCode(String smartCode) {
        this.smartCode = smartCode == null ? null : smartCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.player_code
     *
     * @return the value of t_my_product.player_code
     *
     * @mbggenerated
     */
    public String getPlayerCode() {
        return playerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.player_code
     *
     * @param playerCode the value for t_my_product.player_code
     *
     * @mbggenerated
     */
    public void setPlayerCode(String playerCode) {
        this.playerCode = playerCode == null ? null : playerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.accredit_user
     *
     * @return the value of t_my_product.accredit_user
     *
     * @mbggenerated
     */
    public String getAccreditUser() {
        return accreditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.accredit_user
     *
     * @param accreditUser the value for t_my_product.accredit_user
     *
     * @mbggenerated
     */
    public void setAccreditUser(String accreditUser) {
        this.accreditUser = accreditUser == null ? null : accreditUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.accredit_time
     *
     * @return the value of t_my_product.accredit_time
     *
     * @mbggenerated
     */
    public Date getAccreditTime() {
        return accreditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.accredit_time
     *
     * @param accreditTime the value for t_my_product.accredit_time
     *
     * @mbggenerated
     */
    public void setAccreditTime(Date accreditTime) {
        this.accreditTime = accreditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.accredit_status
     *
     * @return the value of t_my_product.accredit_status
     *
     * @mbggenerated
     */
    public String getAccreditStatus() {
        return accreditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.accredit_status
     *
     * @param accreditStatus the value for t_my_product.accredit_status
     *
     * @mbggenerated
     */
    public void setAccreditStatus(String accreditStatus) {
        this.accreditStatus = accreditStatus == null ? null : accreditStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_my_product.user_id
     *
     * @return the value of t_my_product.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_my_product.user_id
     *
     * @param userId the value for t_my_product.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
    /************************************************************************************************************/

	public Dic getAccreditStatusDic() {
		return accreditStatusDic;
	}

	public void setAccreditStatusDic(Dic accreditStatusDic) {
		this.accreditStatusDic = accreditStatusDic;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public ProductDetail getProductDetail() {
		return productDetail;
	}

	public void setProductDetail(ProductDetail productDetail) {
		this.productDetail = productDetail;
	}
    
}