package com.yfann.web.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OaEmployeeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public OaEmployeeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNull() {
            addCriterion("EMPLOYEE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIsNotNull() {
            addCriterion("EMPLOYEE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdEqualTo(String value) {
            addCriterion("EMPLOYEE_ID =", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotEqualTo(String value) {
            addCriterion("EMPLOYEE_ID <>", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThan(String value) {
            addCriterion("EMPLOYEE_ID >", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdGreaterThanOrEqualTo(String value) {
            addCriterion("EMPLOYEE_ID >=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThan(String value) {
            addCriterion("EMPLOYEE_ID <", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLessThanOrEqualTo(String value) {
            addCriterion("EMPLOYEE_ID <=", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdLike(String value) {
            addCriterion("EMPLOYEE_ID like", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotLike(String value) {
            addCriterion("EMPLOYEE_ID not like", value, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdIn(List<String> values) {
            addCriterion("EMPLOYEE_ID in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotIn(List<String> values) {
            addCriterion("EMPLOYEE_ID not in", values, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdBetween(String value1, String value2) {
            addCriterion("EMPLOYEE_ID between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andEmployeeIdNotBetween(String value1, String value2) {
            addCriterion("EMPLOYEE_ID not between", value1, value2, "employeeId");
            return (Criteria) this;
        }

        public Criteria andNickIsNull() {
            addCriterion("NICK is null");
            return (Criteria) this;
        }

        public Criteria andNickIsNotNull() {
            addCriterion("NICK is not null");
            return (Criteria) this;
        }

        public Criteria andNickEqualTo(String value) {
            addCriterion("NICK =", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotEqualTo(String value) {
            addCriterion("NICK <>", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickGreaterThan(String value) {
            addCriterion("NICK >", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickGreaterThanOrEqualTo(String value) {
            addCriterion("NICK >=", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLessThan(String value) {
            addCriterion("NICK <", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLessThanOrEqualTo(String value) {
            addCriterion("NICK <=", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLike(String value) {
            addCriterion("NICK like", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotLike(String value) {
            addCriterion("NICK not like", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickIn(List<String> values) {
            addCriterion("NICK in", values, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotIn(List<String> values) {
            addCriterion("NICK not in", values, "nick");
            return (Criteria) this;
        }

        public Criteria andNickBetween(String value1, String value2) {
            addCriterion("NICK between", value1, value2, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotBetween(String value1, String value2) {
            addCriterion("NICK not between", value1, value2, "nick");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNull() {
            addCriterion("EMPLOYEE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIsNotNull() {
            addCriterion("EMPLOYEE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameEqualTo(String value) {
            addCriterion("EMPLOYEE_NAME =", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotEqualTo(String value) {
            addCriterion("EMPLOYEE_NAME <>", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThan(String value) {
            addCriterion("EMPLOYEE_NAME >", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameGreaterThanOrEqualTo(String value) {
            addCriterion("EMPLOYEE_NAME >=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThan(String value) {
            addCriterion("EMPLOYEE_NAME <", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLessThanOrEqualTo(String value) {
            addCriterion("EMPLOYEE_NAME <=", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameLike(String value) {
            addCriterion("EMPLOYEE_NAME like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotLike(String value) {
            addCriterion("EMPLOYEE_NAME not like", value, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameIn(List<String> values) {
            addCriterion("EMPLOYEE_NAME in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotIn(List<String> values) {
            addCriterion("EMPLOYEE_NAME not in", values, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameBetween(String value1, String value2) {
            addCriterion("EMPLOYEE_NAME between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andEmployeeNameNotBetween(String value1, String value2) {
            addCriterion("EMPLOYEE_NAME not between", value1, value2, "employeeName");
            return (Criteria) this;
        }

        public Criteria andDepartIdIsNull() {
            addCriterion("DEPART_ID is null");
            return (Criteria) this;
        }

        public Criteria andDepartIdIsNotNull() {
            addCriterion("DEPART_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDepartIdEqualTo(String value) {
            addCriterion("DEPART_ID =", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotEqualTo(String value) {
            addCriterion("DEPART_ID <>", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdGreaterThan(String value) {
            addCriterion("DEPART_ID >", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdGreaterThanOrEqualTo(String value) {
            addCriterion("DEPART_ID >=", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdLessThan(String value) {
            addCriterion("DEPART_ID <", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdLessThanOrEqualTo(String value) {
            addCriterion("DEPART_ID <=", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdLike(String value) {
            addCriterion("DEPART_ID like", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotLike(String value) {
            addCriterion("DEPART_ID not like", value, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdIn(List<String> values) {
            addCriterion("DEPART_ID in", values, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotIn(List<String> values) {
            addCriterion("DEPART_ID not in", values, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdBetween(String value1, String value2) {
            addCriterion("DEPART_ID between", value1, value2, "departId");
            return (Criteria) this;
        }

        public Criteria andDepartIdNotBetween(String value1, String value2) {
            addCriterion("DEPART_ID not between", value1, value2, "departId");
            return (Criteria) this;
        }

        public Criteria andNowPasswordIsNull() {
            addCriterion("NOW_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andNowPasswordIsNotNull() {
            addCriterion("NOW_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andNowPasswordEqualTo(String value) {
            addCriterion("NOW_PASSWORD =", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordNotEqualTo(String value) {
            addCriterion("NOW_PASSWORD <>", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordGreaterThan(String value) {
            addCriterion("NOW_PASSWORD >", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("NOW_PASSWORD >=", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordLessThan(String value) {
            addCriterion("NOW_PASSWORD <", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordLessThanOrEqualTo(String value) {
            addCriterion("NOW_PASSWORD <=", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordLike(String value) {
            addCriterion("NOW_PASSWORD like", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordNotLike(String value) {
            addCriterion("NOW_PASSWORD not like", value, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordIn(List<String> values) {
            addCriterion("NOW_PASSWORD in", values, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordNotIn(List<String> values) {
            addCriterion("NOW_PASSWORD not in", values, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordBetween(String value1, String value2) {
            addCriterion("NOW_PASSWORD between", value1, value2, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andNowPasswordNotBetween(String value1, String value2) {
            addCriterion("NOW_PASSWORD not between", value1, value2, "nowPassword");
            return (Criteria) this;
        }

        public Criteria andSellCodeIsNull() {
            addCriterion("SELL_CODE is null");
            return (Criteria) this;
        }

        public Criteria andSellCodeIsNotNull() {
            addCriterion("SELL_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andSellCodeEqualTo(String value) {
            addCriterion("SELL_CODE =", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeNotEqualTo(String value) {
            addCriterion("SELL_CODE <>", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeGreaterThan(String value) {
            addCriterion("SELL_CODE >", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SELL_CODE >=", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeLessThan(String value) {
            addCriterion("SELL_CODE <", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeLessThanOrEqualTo(String value) {
            addCriterion("SELL_CODE <=", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeLike(String value) {
            addCriterion("SELL_CODE like", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeNotLike(String value) {
            addCriterion("SELL_CODE not like", value, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeIn(List<String> values) {
            addCriterion("SELL_CODE in", values, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeNotIn(List<String> values) {
            addCriterion("SELL_CODE not in", values, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeBetween(String value1, String value2) {
            addCriterion("SELL_CODE between", value1, value2, "sellCode");
            return (Criteria) this;
        }

        public Criteria andSellCodeNotBetween(String value1, String value2) {
            addCriterion("SELL_CODE not between", value1, value2, "sellCode");
            return (Criteria) this;
        }

        public Criteria andOldPasswordIsNull() {
            addCriterion("OLD_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andOldPasswordIsNotNull() {
            addCriterion("OLD_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andOldPasswordEqualTo(String value) {
            addCriterion("OLD_PASSWORD =", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordNotEqualTo(String value) {
            addCriterion("OLD_PASSWORD <>", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordGreaterThan(String value) {
            addCriterion("OLD_PASSWORD >", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("OLD_PASSWORD >=", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordLessThan(String value) {
            addCriterion("OLD_PASSWORD <", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordLessThanOrEqualTo(String value) {
            addCriterion("OLD_PASSWORD <=", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordLike(String value) {
            addCriterion("OLD_PASSWORD like", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordNotLike(String value) {
            addCriterion("OLD_PASSWORD not like", value, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordIn(List<String> values) {
            addCriterion("OLD_PASSWORD in", values, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordNotIn(List<String> values) {
            addCriterion("OLD_PASSWORD not in", values, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordBetween(String value1, String value2) {
            addCriterion("OLD_PASSWORD between", value1, value2, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andOldPasswordNotBetween(String value1, String value2) {
            addCriterion("OLD_PASSWORD not between", value1, value2, "oldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordIsNull() {
            addCriterion("THAN_OLD_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordIsNotNull() {
            addCriterion("THAN_OLD_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordEqualTo(String value) {
            addCriterion("THAN_OLD_PASSWORD =", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordNotEqualTo(String value) {
            addCriterion("THAN_OLD_PASSWORD <>", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordGreaterThan(String value) {
            addCriterion("THAN_OLD_PASSWORD >", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("THAN_OLD_PASSWORD >=", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordLessThan(String value) {
            addCriterion("THAN_OLD_PASSWORD <", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordLessThanOrEqualTo(String value) {
            addCriterion("THAN_OLD_PASSWORD <=", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordLike(String value) {
            addCriterion("THAN_OLD_PASSWORD like", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordNotLike(String value) {
            addCriterion("THAN_OLD_PASSWORD not like", value, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordIn(List<String> values) {
            addCriterion("THAN_OLD_PASSWORD in", values, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordNotIn(List<String> values) {
            addCriterion("THAN_OLD_PASSWORD not in", values, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordBetween(String value1, String value2) {
            addCriterion("THAN_OLD_PASSWORD between", value1, value2, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andThanOldPasswordNotBetween(String value1, String value2) {
            addCriterion("THAN_OLD_PASSWORD not between", value1, value2, "thanOldPassword");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateIsNull() {
            addCriterion("UPDATE_PASSWORD_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateIsNotNull() {
            addCriterion("UPDATE_PASSWORD_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateEqualTo(Date value) {
            addCriterion("UPDATE_PASSWORD_DATE =", value, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateNotEqualTo(Date value) {
            addCriterion("UPDATE_PASSWORD_DATE <>", value, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateGreaterThan(Date value) {
            addCriterion("UPDATE_PASSWORD_DATE >", value, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_PASSWORD_DATE >=", value, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateLessThan(Date value) {
            addCriterion("UPDATE_PASSWORD_DATE <", value, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_PASSWORD_DATE <=", value, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateIn(List<Date> values) {
            addCriterion("UPDATE_PASSWORD_DATE in", values, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateNotIn(List<Date> values) {
            addCriterion("UPDATE_PASSWORD_DATE not in", values, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_PASSWORD_DATE between", value1, value2, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andUpdatePasswordDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_PASSWORD_DATE not between", value1, value2, "updatePasswordDate");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("BIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("BIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("BIRTHDAY =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("BIRTHDAY <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("BIRTHDAY >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("BIRTHDAY <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("BIRTHDAY <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("BIRTHDAY in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("BIRTHDAY not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("BIRTHDAY not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberIsNull() {
            addCriterion("IDCARD_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberIsNotNull() {
            addCriterion("IDCARD_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberEqualTo(String value) {
            addCriterion("IDCARD_NUMBER =", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotEqualTo(String value) {
            addCriterion("IDCARD_NUMBER <>", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberGreaterThan(String value) {
            addCriterion("IDCARD_NUMBER >", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberGreaterThanOrEqualTo(String value) {
            addCriterion("IDCARD_NUMBER >=", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberLessThan(String value) {
            addCriterion("IDCARD_NUMBER <", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberLessThanOrEqualTo(String value) {
            addCriterion("IDCARD_NUMBER <=", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberLike(String value) {
            addCriterion("IDCARD_NUMBER like", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotLike(String value) {
            addCriterion("IDCARD_NUMBER not like", value, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberIn(List<String> values) {
            addCriterion("IDCARD_NUMBER in", values, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotIn(List<String> values) {
            addCriterion("IDCARD_NUMBER not in", values, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberBetween(String value1, String value2) {
            addCriterion("IDCARD_NUMBER between", value1, value2, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andIdcardNumberNotBetween(String value1, String value2) {
            addCriterion("IDCARD_NUMBER not between", value1, value2, "idcardNumber");
            return (Criteria) this;
        }

        public Criteria andEducationIsNull() {
            addCriterion("EDUCATION is null");
            return (Criteria) this;
        }

        public Criteria andEducationIsNotNull() {
            addCriterion("EDUCATION is not null");
            return (Criteria) this;
        }

        public Criteria andEducationEqualTo(String value) {
            addCriterion("EDUCATION =", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotEqualTo(String value) {
            addCriterion("EDUCATION <>", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThan(String value) {
            addCriterion("EDUCATION >", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationGreaterThanOrEqualTo(String value) {
            addCriterion("EDUCATION >=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThan(String value) {
            addCriterion("EDUCATION <", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLessThanOrEqualTo(String value) {
            addCriterion("EDUCATION <=", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationLike(String value) {
            addCriterion("EDUCATION like", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotLike(String value) {
            addCriterion("EDUCATION not like", value, "education");
            return (Criteria) this;
        }

        public Criteria andEducationIn(List<String> values) {
            addCriterion("EDUCATION in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotIn(List<String> values) {
            addCriterion("EDUCATION not in", values, "education");
            return (Criteria) this;
        }

        public Criteria andEducationBetween(String value1, String value2) {
            addCriterion("EDUCATION between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andEducationNotBetween(String value1, String value2) {
            addCriterion("EDUCATION not between", value1, value2, "education");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieIsNull() {
            addCriterion("FOREIGN_COUNTRIE is null");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieIsNotNull() {
            addCriterion("FOREIGN_COUNTRIE is not null");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieEqualTo(String value) {
            addCriterion("FOREIGN_COUNTRIE =", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieNotEqualTo(String value) {
            addCriterion("FOREIGN_COUNTRIE <>", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieGreaterThan(String value) {
            addCriterion("FOREIGN_COUNTRIE >", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieGreaterThanOrEqualTo(String value) {
            addCriterion("FOREIGN_COUNTRIE >=", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieLessThan(String value) {
            addCriterion("FOREIGN_COUNTRIE <", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieLessThanOrEqualTo(String value) {
            addCriterion("FOREIGN_COUNTRIE <=", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieLike(String value) {
            addCriterion("FOREIGN_COUNTRIE like", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieNotLike(String value) {
            addCriterion("FOREIGN_COUNTRIE not like", value, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieIn(List<String> values) {
            addCriterion("FOREIGN_COUNTRIE in", values, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieNotIn(List<String> values) {
            addCriterion("FOREIGN_COUNTRIE not in", values, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieBetween(String value1, String value2) {
            addCriterion("FOREIGN_COUNTRIE between", value1, value2, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andForeignCountrieNotBetween(String value1, String value2) {
            addCriterion("FOREIGN_COUNTRIE not between", value1, value2, "foreignCountrie");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolIsNull() {
            addCriterion("GRADUATE_SCHOOL is null");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolIsNotNull() {
            addCriterion("GRADUATE_SCHOOL is not null");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolEqualTo(String value) {
            addCriterion("GRADUATE_SCHOOL =", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolNotEqualTo(String value) {
            addCriterion("GRADUATE_SCHOOL <>", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolGreaterThan(String value) {
            addCriterion("GRADUATE_SCHOOL >", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("GRADUATE_SCHOOL >=", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolLessThan(String value) {
            addCriterion("GRADUATE_SCHOOL <", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolLessThanOrEqualTo(String value) {
            addCriterion("GRADUATE_SCHOOL <=", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolLike(String value) {
            addCriterion("GRADUATE_SCHOOL like", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolNotLike(String value) {
            addCriterion("GRADUATE_SCHOOL not like", value, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolIn(List<String> values) {
            addCriterion("GRADUATE_SCHOOL in", values, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolNotIn(List<String> values) {
            addCriterion("GRADUATE_SCHOOL not in", values, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolBetween(String value1, String value2) {
            addCriterion("GRADUATE_SCHOOL between", value1, value2, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andGraduateSchoolNotBetween(String value1, String value2) {
            addCriterion("GRADUATE_SCHOOL not between", value1, value2, "graduateSchool");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("PHONE_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("PHONE_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("PHONE_NUMBER =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("PHONE_NUMBER <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("PHONE_NUMBER >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("PHONE_NUMBER <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("PHONE_NUMBER <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("PHONE_NUMBER like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("PHONE_NUMBER not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("PHONE_NUMBER in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("PHONE_NUMBER not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("PHONE_NUMBER between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("PHONE_NUMBER not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("IP in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("IP not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andCountrieIsNull() {
            addCriterion("COUNTRIE is null");
            return (Criteria) this;
        }

        public Criteria andCountrieIsNotNull() {
            addCriterion("COUNTRIE is not null");
            return (Criteria) this;
        }

        public Criteria andCountrieEqualTo(String value) {
            addCriterion("COUNTRIE =", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieNotEqualTo(String value) {
            addCriterion("COUNTRIE <>", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieGreaterThan(String value) {
            addCriterion("COUNTRIE >", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieGreaterThanOrEqualTo(String value) {
            addCriterion("COUNTRIE >=", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieLessThan(String value) {
            addCriterion("COUNTRIE <", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieLessThanOrEqualTo(String value) {
            addCriterion("COUNTRIE <=", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieLike(String value) {
            addCriterion("COUNTRIE like", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieNotLike(String value) {
            addCriterion("COUNTRIE not like", value, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieIn(List<String> values) {
            addCriterion("COUNTRIE in", values, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieNotIn(List<String> values) {
            addCriterion("COUNTRIE not in", values, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieBetween(String value1, String value2) {
            addCriterion("COUNTRIE between", value1, value2, "countrie");
            return (Criteria) this;
        }

        public Criteria andCountrieNotBetween(String value1, String value2) {
            addCriterion("COUNTRIE not between", value1, value2, "countrie");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityIsNull() {
            addCriterion("PROVINCE_AND_CITY is null");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityIsNotNull() {
            addCriterion("PROVINCE_AND_CITY is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityEqualTo(String value) {
            addCriterion("PROVINCE_AND_CITY =", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityNotEqualTo(String value) {
            addCriterion("PROVINCE_AND_CITY <>", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityGreaterThan(String value) {
            addCriterion("PROVINCE_AND_CITY >", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityGreaterThanOrEqualTo(String value) {
            addCriterion("PROVINCE_AND_CITY >=", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityLessThan(String value) {
            addCriterion("PROVINCE_AND_CITY <", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityLessThanOrEqualTo(String value) {
            addCriterion("PROVINCE_AND_CITY <=", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityLike(String value) {
            addCriterion("PROVINCE_AND_CITY like", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityNotLike(String value) {
            addCriterion("PROVINCE_AND_CITY not like", value, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityIn(List<String> values) {
            addCriterion("PROVINCE_AND_CITY in", values, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityNotIn(List<String> values) {
            addCriterion("PROVINCE_AND_CITY not in", values, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityBetween(String value1, String value2) {
            addCriterion("PROVINCE_AND_CITY between", value1, value2, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andProvinceAndCityNotBetween(String value1, String value2) {
            addCriterion("PROVINCE_AND_CITY not between", value1, value2, "provinceAndCity");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNull() {
            addCriterion("ZIP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andZipCodeIsNotNull() {
            addCriterion("ZIP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andZipCodeEqualTo(String value) {
            addCriterion("ZIP_CODE =", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotEqualTo(String value) {
            addCriterion("ZIP_CODE <>", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThan(String value) {
            addCriterion("ZIP_CODE >", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE >=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThan(String value) {
            addCriterion("ZIP_CODE <", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLessThanOrEqualTo(String value) {
            addCriterion("ZIP_CODE <=", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeLike(String value) {
            addCriterion("ZIP_CODE like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotLike(String value) {
            addCriterion("ZIP_CODE not like", value, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeIn(List<String> values) {
            addCriterion("ZIP_CODE in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotIn(List<String> values) {
            addCriterion("ZIP_CODE not in", values, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeBetween(String value1, String value2) {
            addCriterion("ZIP_CODE between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andZipCodeNotBetween(String value1, String value2) {
            addCriterion("ZIP_CODE not between", value1, value2, "zipCode");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("EMAIL is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("EMAIL is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("EMAIL =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("EMAIL <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("EMAIL >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("EMAIL >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("EMAIL <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("EMAIL <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("EMAIL like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("EMAIL not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("EMAIL in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("EMAIL not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("EMAIL between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("EMAIL not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andQqIsNull() {
            addCriterion("QQ is null");
            return (Criteria) this;
        }

        public Criteria andQqIsNotNull() {
            addCriterion("QQ is not null");
            return (Criteria) this;
        }

        public Criteria andQqEqualTo(String value) {
            addCriterion("QQ =", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotEqualTo(String value) {
            addCriterion("QQ <>", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThan(String value) {
            addCriterion("QQ >", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqGreaterThanOrEqualTo(String value) {
            addCriterion("QQ >=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThan(String value) {
            addCriterion("QQ <", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLessThanOrEqualTo(String value) {
            addCriterion("QQ <=", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqLike(String value) {
            addCriterion("QQ like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotLike(String value) {
            addCriterion("QQ not like", value, "qq");
            return (Criteria) this;
        }

        public Criteria andQqIn(List<String> values) {
            addCriterion("QQ in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotIn(List<String> values) {
            addCriterion("QQ not in", values, "qq");
            return (Criteria) this;
        }

        public Criteria andQqBetween(String value1, String value2) {
            addCriterion("QQ between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andQqNotBetween(String value1, String value2) {
            addCriterion("QQ not between", value1, value2, "qq");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeIsNull() {
            addCriterion("PAGE_COUNT_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeIsNotNull() {
            addCriterion("PAGE_COUNT_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeEqualTo(Boolean value) {
            addCriterion("PAGE_COUNT_SIZE =", value, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeNotEqualTo(Boolean value) {
            addCriterion("PAGE_COUNT_SIZE <>", value, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeGreaterThan(Boolean value) {
            addCriterion("PAGE_COUNT_SIZE >", value, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("PAGE_COUNT_SIZE >=", value, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeLessThan(Boolean value) {
            addCriterion("PAGE_COUNT_SIZE <", value, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeLessThanOrEqualTo(Boolean value) {
            addCriterion("PAGE_COUNT_SIZE <=", value, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeIn(List<Boolean> values) {
            addCriterion("PAGE_COUNT_SIZE in", values, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeNotIn(List<Boolean> values) {
            addCriterion("PAGE_COUNT_SIZE not in", values, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeBetween(Boolean value1, Boolean value2) {
            addCriterion("PAGE_COUNT_SIZE between", value1, value2, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andPageCountSizeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("PAGE_COUNT_SIZE not between", value1, value2, "pageCountSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeIsNull() {
            addCriterion("GROUP_PAGE_SIZE is null");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeIsNotNull() {
            addCriterion("GROUP_PAGE_SIZE is not null");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeEqualTo(String value) {
            addCriterion("GROUP_PAGE_SIZE =", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeNotEqualTo(String value) {
            addCriterion("GROUP_PAGE_SIZE <>", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeGreaterThan(String value) {
            addCriterion("GROUP_PAGE_SIZE >", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_PAGE_SIZE >=", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeLessThan(String value) {
            addCriterion("GROUP_PAGE_SIZE <", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeLessThanOrEqualTo(String value) {
            addCriterion("GROUP_PAGE_SIZE <=", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeLike(String value) {
            addCriterion("GROUP_PAGE_SIZE like", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeNotLike(String value) {
            addCriterion("GROUP_PAGE_SIZE not like", value, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeIn(List<String> values) {
            addCriterion("GROUP_PAGE_SIZE in", values, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeNotIn(List<String> values) {
            addCriterion("GROUP_PAGE_SIZE not in", values, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeBetween(String value1, String value2) {
            addCriterion("GROUP_PAGE_SIZE between", value1, value2, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andGroupPageSizeNotBetween(String value1, String value2) {
            addCriterion("GROUP_PAGE_SIZE not between", value1, value2, "groupPageSize");
            return (Criteria) this;
        }

        public Criteria andShowStyleIsNull() {
            addCriterion("SHOW_STYLE is null");
            return (Criteria) this;
        }

        public Criteria andShowStyleIsNotNull() {
            addCriterion("SHOW_STYLE is not null");
            return (Criteria) this;
        }

        public Criteria andShowStyleEqualTo(String value) {
            addCriterion("SHOW_STYLE =", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleNotEqualTo(String value) {
            addCriterion("SHOW_STYLE <>", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleGreaterThan(String value) {
            addCriterion("SHOW_STYLE >", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleGreaterThanOrEqualTo(String value) {
            addCriterion("SHOW_STYLE >=", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleLessThan(String value) {
            addCriterion("SHOW_STYLE <", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleLessThanOrEqualTo(String value) {
            addCriterion("SHOW_STYLE <=", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleLike(String value) {
            addCriterion("SHOW_STYLE like", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleNotLike(String value) {
            addCriterion("SHOW_STYLE not like", value, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleIn(List<String> values) {
            addCriterion("SHOW_STYLE in", values, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleNotIn(List<String> values) {
            addCriterion("SHOW_STYLE not in", values, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleBetween(String value1, String value2) {
            addCriterion("SHOW_STYLE between", value1, value2, "showStyle");
            return (Criteria) this;
        }

        public Criteria andShowStyleNotBetween(String value1, String value2) {
            addCriterion("SHOW_STYLE not between", value1, value2, "showStyle");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNull() {
            addCriterion("LAST_LOGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIsNotNull() {
            addCriterion("LAST_LOGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME =", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME <>", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThan(Date value) {
            addCriterion("LAST_LOGIN_TIME >", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME >=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThan(Date value) {
            addCriterion("LAST_LOGIN_TIME <", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("LAST_LOGIN_TIME <=", value, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeIn(List<Date> values) {
            addCriterion("LAST_LOGIN_TIME in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotIn(List<Date> values) {
            addCriterion("LAST_LOGIN_TIME not in", values, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeBetween(Date value1, Date value2) {
            addCriterion("LAST_LOGIN_TIME between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("LAST_LOGIN_TIME not between", value1, value2, "lastLoginTime");
            return (Criteria) this;
        }

        public Criteria andLoginCountIsNull() {
            addCriterion("LOGIN_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andLoginCountIsNotNull() {
            addCriterion("LOGIN_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andLoginCountEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT =", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT <>", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountGreaterThan(Integer value) {
            addCriterion("LOGIN_COUNT >", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT >=", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountLessThan(Integer value) {
            addCriterion("LOGIN_COUNT <", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountLessThanOrEqualTo(Integer value) {
            addCriterion("LOGIN_COUNT <=", value, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountIn(List<Integer> values) {
            addCriterion("LOGIN_COUNT in", values, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotIn(List<Integer> values) {
            addCriterion("LOGIN_COUNT not in", values, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountBetween(Integer value1, Integer value2) {
            addCriterion("LOGIN_COUNT between", value1, value2, "loginCount");
            return (Criteria) this;
        }

        public Criteria andLoginCountNotBetween(Integer value1, Integer value2) {
            addCriterion("LOGIN_COUNT not between", value1, value2, "loginCount");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagIsNull() {
            addCriterion("SELECTED_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagIsNotNull() {
            addCriterion("SELECTED_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagEqualTo(String value) {
            addCriterion("SELECTED_FLAG =", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagNotEqualTo(String value) {
            addCriterion("SELECTED_FLAG <>", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagGreaterThan(String value) {
            addCriterion("SELECTED_FLAG >", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("SELECTED_FLAG >=", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagLessThan(String value) {
            addCriterion("SELECTED_FLAG <", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagLessThanOrEqualTo(String value) {
            addCriterion("SELECTED_FLAG <=", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagLike(String value) {
            addCriterion("SELECTED_FLAG like", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagNotLike(String value) {
            addCriterion("SELECTED_FLAG not like", value, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagIn(List<String> values) {
            addCriterion("SELECTED_FLAG in", values, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagNotIn(List<String> values) {
            addCriterion("SELECTED_FLAG not in", values, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagBetween(String value1, String value2) {
            addCriterion("SELECTED_FLAG between", value1, value2, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andSelectedFlagNotBetween(String value1, String value2) {
            addCriterion("SELECTED_FLAG not between", value1, value2, "selectedFlag");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andLoginDateIsNull() {
            addCriterion("LOGIN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLoginDateIsNotNull() {
            addCriterion("LOGIN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLoginDateEqualTo(Date value) {
            addCriterion("LOGIN_DATE =", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotEqualTo(Date value) {
            addCriterion("LOGIN_DATE <>", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateGreaterThan(Date value) {
            addCriterion("LOGIN_DATE >", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LOGIN_DATE >=", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateLessThan(Date value) {
            addCriterion("LOGIN_DATE <", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateLessThanOrEqualTo(Date value) {
            addCriterion("LOGIN_DATE <=", value, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateIn(List<Date> values) {
            addCriterion("LOGIN_DATE in", values, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotIn(List<Date> values) {
            addCriterion("LOGIN_DATE not in", values, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateBetween(Date value1, Date value2) {
            addCriterion("LOGIN_DATE between", value1, value2, "loginDate");
            return (Criteria) this;
        }

        public Criteria andLoginDateNotBetween(Date value1, Date value2) {
            addCriterion("LOGIN_DATE not between", value1, value2, "loginDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oa_employee
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_oa_employee
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}