package com.yfann.web.pojo;

import java.math.BigDecimal;

public class OaRoyalties {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_royalties.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_royalties.UPPER_LIMIT
     *
     * @mbggenerated
     */
    private Integer upperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_royalties.LOWER_LIMIT
     *
     * @mbggenerated
     */
    private Integer lowerLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_royalties.SCALE
     *
     * @mbggenerated
     */
    private BigDecimal scale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_royalties.ID
     *
     * @return the value of t_oa_royalties.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_royalties.ID
     *
     * @param id the value for t_oa_royalties.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_royalties.UPPER_LIMIT
     *
     * @return the value of t_oa_royalties.UPPER_LIMIT
     *
     * @mbggenerated
     */
    public Integer getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_royalties.UPPER_LIMIT
     *
     * @param upperLimit the value for t_oa_royalties.UPPER_LIMIT
     *
     * @mbggenerated
     */
    public void setUpperLimit(Integer upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_royalties.LOWER_LIMIT
     *
     * @return the value of t_oa_royalties.LOWER_LIMIT
     *
     * @mbggenerated
     */
    public Integer getLowerLimit() {
        return lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_royalties.LOWER_LIMIT
     *
     * @param lowerLimit the value for t_oa_royalties.LOWER_LIMIT
     *
     * @mbggenerated
     */
    public void setLowerLimit(Integer lowerLimit) {
        this.lowerLimit = lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_royalties.SCALE
     *
     * @return the value of t_oa_royalties.SCALE
     *
     * @mbggenerated
     */
    public BigDecimal getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_royalties.SCALE
     *
     * @param scale the value for t_oa_royalties.SCALE
     *
     * @mbggenerated
     */
    public void setScale(BigDecimal scale) {
        this.scale = scale;
    }
}