package com.yfann.web.pojo;

import java.util.Date;

public class OaSales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_sales.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_sales.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    private String employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_sales.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_sales.SALES_CODE
     *
     * @mbggenerated
     */
    private String salesCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_oa_sales.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_sales.ID
     *
     * @return the value of t_oa_sales.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_sales.ID
     *
     * @param id the value for t_oa_sales.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_sales.EMPLOYEE_ID
     *
     * @return the value of t_oa_sales.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_sales.EMPLOYEE_ID
     *
     * @param employeeId the value for t_oa_sales.EMPLOYEE_ID
     *
     * @mbggenerated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_sales.USER_ID
     *
     * @return the value of t_oa_sales.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_sales.USER_ID
     *
     * @param userId the value for t_oa_sales.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_sales.SALES_CODE
     *
     * @return the value of t_oa_sales.SALES_CODE
     *
     * @mbggenerated
     */
    public String getSalesCode() {
        return salesCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_sales.SALES_CODE
     *
     * @param salesCode the value for t_oa_sales.SALES_CODE
     *
     * @mbggenerated
     */
    public void setSalesCode(String salesCode) {
        this.salesCode = salesCode == null ? null : salesCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_oa_sales.CREATE_TIME
     *
     * @return the value of t_oa_sales.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_oa_sales.CREATE_TIME
     *
     * @param createTime the value for t_oa_sales.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}