package com.yfann.web.pojo;

import java.util.Date;

public class ProductDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail.video_name
     *
     * @mbggenerated
     */
    private String videoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail.video_url
     *
     * @mbggenerated
     */
    private String videoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail.attachment_file_name
     *
     * @mbggenerated
     */
    private String attachmentFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail.cloud_pan_code
     *
     * @mbggenerated
     */
    private String cloudPanCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail.id
     *
     * @return the value of t_product_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail.id
     *
     * @param id the value for t_product_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail.product_id
     *
     * @return the value of t_product_detail.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail.product_id
     *
     * @param productId the value for t_product_detail.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail.video_name
     *
     * @return the value of t_product_detail.video_name
     *
     * @mbggenerated
     */
    public String getVideoName() {
        return videoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail.video_name
     *
     * @param videoName the value for t_product_detail.video_name
     *
     * @mbggenerated
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName == null ? null : videoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail.video_url
     *
     * @return the value of t_product_detail.video_url
     *
     * @mbggenerated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail.video_url
     *
     * @param videoUrl the value for t_product_detail.video_url
     *
     * @mbggenerated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail.create_time
     *
     * @return the value of t_product_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail.create_time
     *
     * @param createTime the value for t_product_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail.attachment_file_name
     *
     * @return the value of t_product_detail.attachment_file_name
     *
     * @mbggenerated
     */
    public String getAttachmentFileName() {
        return attachmentFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail.attachment_file_name
     *
     * @param attachmentFileName the value for t_product_detail.attachment_file_name
     *
     * @mbggenerated
     */
    public void setAttachmentFileName(String attachmentFileName) {
        this.attachmentFileName = attachmentFileName == null ? null : attachmentFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail.cloud_pan_code
     *
     * @return the value of t_product_detail.cloud_pan_code
     *
     * @mbggenerated
     */
    public String getCloudPanCode() {
        return cloudPanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail.cloud_pan_code
     *
     * @param cloudPanCode the value for t_product_detail.cloud_pan_code
     *
     * @mbggenerated
     */
    public void setCloudPanCode(String cloudPanCode) {
        this.cloudPanCode = cloudPanCode == null ? null : cloudPanCode.trim();
    }
}