package com.yfann.web.pojo;

public class ProductDetailAvatar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail_avatar.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail_avatar.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_product_detail_avatar.avatar_img
     *
     * @mbggenerated
     */
    private byte[] avatarImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail_avatar.id
     *
     * @return the value of t_product_detail_avatar.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail_avatar.id
     *
     * @param id the value for t_product_detail_avatar.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail_avatar.product_id
     *
     * @return the value of t_product_detail_avatar.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail_avatar.product_id
     *
     * @param productId the value for t_product_detail_avatar.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_product_detail_avatar.avatar_img
     *
     * @return the value of t_product_detail_avatar.avatar_img
     *
     * @mbggenerated
     */
    public byte[] getAvatarImg() {
        return avatarImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_product_detail_avatar.avatar_img
     *
     * @param avatarImg the value for t_product_detail_avatar.avatar_img
     *
     * @mbggenerated
     */
    public void setAvatarImg(byte[] avatarImg) {
        this.avatarImg = avatarImg;
    }
}