package com.yfann.web.dao;

import com.yfann.web.pojo.ApplyMoney;
import com.yfann.web.pojo.ApplyMoneyExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ApplyMoneyMapper {
	/**
	 * 根据传入参数查询相应的申请记录
	 * @param applyMoney
	 * @return
	 */
	int selectCountByApply(ApplyMoney applyMoney);
	List<ApplyMoney> selectListByApply(ApplyMoney applyMoney);
	List<ApplyMoney> selectListByApply(ApplyMoney applyMoney, RowBounds rowBounds);
	/**
	 * 分页获取
	 * 
	 * @param example
	 * @param rowBounds
	 * @return
	 */
	List<ApplyMoney> selectByExample(ApplyMoneyExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int countByExample(ApplyMoneyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int deleteByExample(ApplyMoneyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int insert(ApplyMoney record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int insertSelective(ApplyMoney record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	List<ApplyMoney> selectByExample(ApplyMoneyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	ApplyMoney selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ApplyMoney record,
			@Param("example") ApplyMoneyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ApplyMoney record, @Param("example") ApplyMoneyExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ApplyMoney record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_apply_money
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ApplyMoney record);
}