package com.yfann.web.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.yfann.web.pojo.BuyCar;
import com.yfann.web.pojo.BuyCarExample;

public interface BuyCarMapper {
	/**
	 *根据map条件查询购物车列表 不分页
	 * @param parames
	 * @return
	 */
	List<BuyCar> selectBuyCarListByParames(Map<String, Object> parames);
	/**
	 * 根据用户ID删除购物车
	 * @param userId
	 * @return
	 */
	int deleteBuyCarByUserId(String userId); 
	/**
	 * 根据产品id增加数量
	 * @param productId
	 * @return
	 */
	int updateAddBuyCountByProductId(Map<String, Object> parames);
	/**
	 * 根据产品Id查询购物车
	 * @param productId
	 * @return
	 */
	BuyCar selectBuyCarByProductId(Map<String,Object> parames);
	/**
	 * 购物车商品数量+1
	 * @param id
	 * @return
	 */
	int updateAddBuyCarCountById(String id);
	
	/**
	 * 购物车商品数量-1
	 * @param id
	 * @return
	 */
	int updateSubBuyCarCountById(String id);
	/**
	 * 查询产品数量
	 * @param paramer
	 * @return
	 */
	int selectBuyCarCountByParamer(Map<String,Object> paramer);
	/**
	 * 查询购物车
	 * @param paramer
	 * @param rowBounds
	 * @return
	 */
	List<BuyCar> selectBuyCarListByParamer(Map<String,Object> paramer,RowBounds rowBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int countByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int deleteByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int insert(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int insertSelective(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    List<BuyCar> selectByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    BuyCar selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BuyCar record, @Param("example") BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BuyCar record, @Param("example") BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BuyCar record);
}