package com.yfann.web.dao;

import com.yfann.web.pojo.BuyCar;
import com.yfann.web.pojo.BuyCarExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BuyCarMapper {
	/**
	 * 查询购物车根据订单ID
	 * @param productId
	 * @return
	 */
	BuyCar selectBuyCarByProductId(String productId);
	/**
	 * 更新购物车产品数量+1
	 * @param productId
	 * @return
	 */
	int updateProductOnBuyCar(String productId);
	/**
	 * 查询产品数量
	 * @param paramer
	 * @return
	 */
	int selectBuyCarCountByParamer(Map<String,Object> paramer);
	/**
	 * 查询购物车
	 * @param paramer
	 * @param rowBounds
	 * @return
	 */
	List<BuyCar> selectBuyCarListByParamer(Map<String,Object> paramer,RowBounds rowBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int countByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int deleteByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int insert(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int insertSelective(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    List<BuyCar> selectByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    BuyCar selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BuyCar record, @Param("example") BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BuyCar record, @Param("example") BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_buy_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BuyCar record);
}