package com.yfann.web.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yfann.web.pojo.Dic;
import com.yfann.web.pojo.DicExample;

public interface DicMapper {
	/**
	 * 查询对应的产品状态
	 * @param dicCode
	 * @return
	 */
	Dic selectProductStatusDic(String dicCode);
	/**
	 *根据编码查询我的消息状态字典信息
	 * @param dicCode
	 * @return
	 */
	Dic selectMsgStatusByCode(String dicCode);
	/**
	 * 根据编码查询满意度
	 * @param o
	 * @return
	 */
	Dic selectProductSatisfactionDicByDicCode(String dicCode);
	/**
	 * 根据DicType查询字典
	 * @param dicType
	 * @return
	 */
	List<Dic> selectDicListByDicType(String dicType);
	/**
	 * 根据编码查询订单状态
	 * @param parames
	 * @return
	 */
	Dic selectOrderStatusDicByDicCode(String dicCode);
	/**
	 * 根据编码查询授权码授权状态
	 * @param parames
	 * @return
	 */
	Dic selectPlayerCodeAccreditDicByDicCode(String dicCode);
	/****************************************************************************************************/
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int countByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int deleteByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int insert(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int insertSelective(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    List<Dic> selectByExample(DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    Dic selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Dic record, @Param("example") DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Dic record, @Param("example") DicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dic record);
}