package com.yfann.web.dao;

import com.yfann.web.pojo.GroupProduct;
import com.yfann.web.pojo.GroupProductExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GroupProductMapper {
	/**
	 * 分页查询
	 * 
	 * @param example
	 * @param rowBounds
	 * @return
	 */
	List<GroupProduct> selectByExample(GroupProductExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int countByExample(GroupProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int deleteByExample(GroupProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int insert(GroupProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int insertSelective(GroupProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	List<GroupProduct> selectByExample(GroupProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	GroupProduct selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") GroupProduct record,
			@Param("example") GroupProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") GroupProduct record, @Param("example") GroupProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(GroupProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_group_product
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(GroupProduct record);
}