package com.yfann.web.dao;

import com.yfann.web.pojo.Message;
import com.yfann.web.pojo.MessageExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MessageMapper {
	/**
	 * 分页查询
	 * 
	 * @param example
	 * @param rowBounds
	 * @return
	 */
	List<Message> selectByExample(MessageExample example, RowBounds rowBounds);

	int countByMessageParam(Message message);

	List<Message> selectByMessageParam(Message message, RowBounds rowBounds);

	List<Message> selectByMessageParam(Message message);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int countByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int deleteByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int insert(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int insertSelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	List<Message> selectByExample(MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	Message selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Message record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_sys_message
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Message record);
}