package com.yfann.web.dao;

import com.yfann.web.pojo.MyProduct;
import com.yfann.web.pojo.MyProductExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MyProductMapper {
	/**
	 * 根据主键查询我的课程
	 * @param id
	 * @return
	 */
	MyProduct selectMyProductById(String id);
	/**
	 * 根据条件查询我的课程列表
	 * @param parames
	 * @param rowBounds
	 * @return
	 */
	List<MyProduct> selectMyProductListByParames(Map<String, Object> parames,RowBounds rowBounds);
	/**
	 * 根据条件查询我的课程列表数量
	 * @param parames
	 * @param rowBounds
	 * @return
	 */
	int selectMyProductListCountByParames(Map<String, Object> parames);
	/**************************************************************************************************/
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int countByExample(MyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int deleteByExample(MyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int insert(MyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int insertSelective(MyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    List<MyProduct> selectByExample(MyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    MyProduct selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MyProduct record, @Param("example") MyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MyProduct record, @Param("example") MyProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_my_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyProduct record);
}