package com.yfann.web.dao;

import com.yfann.web.pojo.OaMenu;
import com.yfann.web.pojo.OaMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OaMenuMapper {
	/**
	 * 查询角色所关联的菜单表
	 * 
	 * @param menuId
	 * @return
	 */
	List<OaMenu> selectByRole(String roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int countByExample(OaMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int deleteByExample(OaMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int insert(OaMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int insertSelective(OaMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	List<OaMenu> selectByExample(OaMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	OaMenu selectByPrimaryKey(String menuId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") OaMenu record, @Param("example") OaMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") OaMenu record, @Param("example") OaMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OaMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_menu
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OaMenu record);
}