package com.yfann.web.dao;

import com.yfann.web.pojo.OaRoyalties;
import com.yfann.web.pojo.OaRoyaltiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OaRoyaltiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int countByExample(OaRoyaltiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int deleteByExample(OaRoyaltiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int insert(OaRoyalties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int insertSelective(OaRoyalties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    List<OaRoyalties> selectByExample(OaRoyaltiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    OaRoyalties selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OaRoyalties record, @Param("example") OaRoyaltiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OaRoyalties record, @Param("example") OaRoyaltiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaRoyalties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_royalties
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaRoyalties record);
}