package com.yfann.web.dao;

import com.yfann.web.pojo.OaSalesChampion;
import com.yfann.web.pojo.OaSalesChampionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OaSalesChampionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int countByExample(OaSalesChampionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int deleteByExample(OaSalesChampionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int insert(OaSalesChampion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int insertSelective(OaSalesChampion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    List<OaSalesChampion> selectByExample(OaSalesChampionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    OaSalesChampion selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OaSalesChampion record, @Param("example") OaSalesChampionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OaSalesChampion record, @Param("example") OaSalesChampionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OaSalesChampion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_oa_sales_champion
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OaSalesChampion record);
}