package com.yfann.web.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.yfann.web.pojo.OaSales;
import com.yfann.web.pojo.OaSalesExample;
import com.yfann.web.vo.SalesCount;

public interface OaSalesMapper {
	/**
	 * 根据条件统计销售信息
	 * 
	 * @param date
	 * @return
	 */
	List<SalesCount> selectCount(String date);

	/**
	 * 分页查询
	 * 
	 * @param example
	 * @param rowBounds
	 * @return
	 */
	List<OaSales> selectByExample(OaSalesExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int countByExample(OaSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int deleteByExample(OaSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int insert(OaSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int insertSelective(OaSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	List<OaSales> selectByExample(OaSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	OaSales selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") OaSales record, @Param("example") OaSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") OaSales record, @Param("example") OaSalesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(OaSales record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_oa_sales
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OaSales record);
}