package com.yfann.web.dao;

import com.yfann.web.pojo.Product;
import com.yfann.web.pojo.ProductExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductMapper {
	
	List <Product> selectPerfectListByProductParam(Map<String, Object> paramer);
	int selectCountByProductParam(Product product);
	List<Product> selectListByProductParam(Product product);
	List<Product> selectListByProductParam(Product product, RowBounds rowBounds);
	/**
	 * 分页查询
	 * 
	 * @param example
	 * @param rowBounds
	 * @return
	 */
	List<Product> selectByExample(ProductExample example, RowBounds rowBounds);

	/**
	 * 查询产品根据产品Id
	 * 
	 * @param productId
	 * @return
	 */
	Product selectProductByProductId(String id);

	/**
	 * 根据多个产品ID查询产品
	 * 
	 * @param productIds
	 * @return
	 */
	List<Product> selectProductListByIds(List<String> productIds);

	/**
	 * 根据条件返回产品列表
	 * 
	 * @param paramer
	 * @param rowBounds
	 * @return
	 */
	List<Product> selectProductByParamer(Product product, RowBounds rowBounds);
	List<Product> selectProductByParamer(Product product);
	/**
	 * 根据条件返回产品总数
	 * 
	 * @param paramer
	 * 
	 * @return
	 */
	int selectProductCountByParamer(Product product);

	/**
	 * 根据课程ID查询缩略图
	 * 
	 * @param id
	 * @return
	 */
	List<Product> selectProductSmallImgById(String id);

	/*************************************************************************************************************************/
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int countByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int deleteByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int insert(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int insertSelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	List<Product> selectByExampleWithBLOBs(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	List<Product> selectByExample(ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	Product selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") Product record, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int updateByExampleWithBLOBs(@Param("record") Product record, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") Product record, @Param("example") ProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeyWithBLOBs(Product record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_product
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Product record);
}