package com.yfann.web.dao;

import com.yfann.web.pojo.ProductAppraise;
import com.yfann.web.pojo.ProductAppraiseExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ProductAppraiseMapper {
	/**
	 * 根据参数查询评论数量
	 * @param productId
	 * @return
	 */
	List<ProductAppraise> selectProductAppraiseListByParames(Map<String, Object> parames,RowBounds rowBounds);
	/**
	 * 根据参数查询评论数量
	 * @param parames
	 * @return
	 */
	int selectProductAppraiseListCountByParames(Map<String, Object> parames);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_appraise
     *
     * @mbggenerated
     */
    int countByExample(ProductAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_appraise
     *
     * @mbggenerated
     */
    int deleteByExample(ProductAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_appraise
     *
     * @mbggenerated
     */
    int insert(ProductAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_appraise
     *
     * @mbggenerated
     */
    int insertSelective(ProductAppraise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_appraise
     *
     * @mbggenerated
     */
    List<ProductAppraise> selectByExample(ProductAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_appraise
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductAppraise record, @Param("example") ProductAppraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_appraise
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductAppraise record, @Param("example") ProductAppraiseExample example);
}