package com.yfann.web.dao;

import com.yfann.web.pojo.ProductDetailImage;
import com.yfann.web.pojo.ProductDetailImageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductDetailImageMapper {
	/**
	 * 根据产品Id查询产品详情图片
	 * @param productId
	 * @return
	 */
	List<ProductDetailImage> selectProductDetailImageByProductId(String productId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int countByExample(ProductDetailImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int deleteByExample(ProductDetailImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int insert(ProductDetailImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int insertSelective(ProductDetailImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    List<ProductDetailImage> selectByExampleWithBLOBs(ProductDetailImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    List<ProductDetailImage> selectByExample(ProductDetailImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    ProductDetailImage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductDetailImage record, @Param("example") ProductDetailImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProductDetailImage record, @Param("example") ProductDetailImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductDetailImage record, @Param("example") ProductDetailImageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductDetailImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProductDetailImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_image
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDetailImage record);
}