package com.yfann.web.dao;

import com.yfann.web.pojo.ProductDetailAvatar;
import com.yfann.web.pojo.ProductDetailAvatarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductDetailAvatarMapper {
	/**
	 * 查询课程截图根据产品Id
	 * @param productId
	 * @return
	 */
	List<ProductDetailAvatar> selectProductDetailAvatarByListByProductId(String productId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int countByExample(ProductDetailAvatarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int deleteByExample(ProductDetailAvatarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int insert(ProductDetailAvatar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int insertSelective(ProductDetailAvatar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    List<ProductDetailAvatar> selectByExampleWithBLOBs(ProductDetailAvatarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    List<ProductDetailAvatar> selectByExample(ProductDetailAvatarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    ProductDetailAvatar selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductDetailAvatar record, @Param("example") ProductDetailAvatarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ProductDetailAvatar record, @Param("example") ProductDetailAvatarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductDetailAvatar record, @Param("example") ProductDetailAvatarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductDetailAvatar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ProductDetailAvatar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product_detail_avatar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDetailAvatar record);
}