package com.yfann.web.dao;

import com.yfann.web.pojo.PublicMessage;
import com.yfann.web.pojo.PublicMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublicMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int countByExample(PublicMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int deleteByExample(PublicMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int insert(PublicMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int insertSelective(PublicMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    List<PublicMessage> selectByExample(PublicMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    PublicMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PublicMessage record, @Param("example") PublicMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PublicMessage record, @Param("example") PublicMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PublicMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_public_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PublicMessage record);
}